version: '3.5'

services:

  build_whl:
    build:
      context: .
      args:
        # TAG: choose python version, from https://hub.docker.com/_/python
        - IMAGE=python
        - TAG=alpine
        - MIRROR=mirrors.aliyun.com
      #  - MIRROR=mirrors.ustc.edu.cn
      dockerfile: Dockerfile


    container_name: build_box
    image: build_whl:alpine
    environment:
      - SRC_LINK=https://github.com/python-greenlet/greenlet/archive/0.4.14.tar.gz

    # if you want to mount a local path,
    # mount it to the container path /whl.
    volumes:
      #      - "$(local path):/whl"
      - "./dist:/dist"
      - "./build_dist.sh:/whl/build_dist.sh"
    command: ["/bin/sh", "/whl/build_dist.sh"]
