version: '3.5'

services:

  build_whl:
    container_name: build_box
    image: build_whl:$TAG
    environment:
      - SRC_LINK=$SRC_LINK
      - PRE_COMMAND=$PRE_COMMAND

    # if you want to mount a local path,
    # mount it to the container path /whl.
    volumes:
      #      - "$(local path):/whl"
      - "./dist:/dist"
      - "./build_dist.sh:/whl/build_dist.sh"
    command: ["/bin/sh", "/whl/build_dist.sh"]
