version: '3.5'

services:

  build_whl:
    build:
      context: .
      args:
        # TAG: choose python version, from https://hub.docker.com/_/python
        - IMAGE_TAG=python:2.7-slim
        - MIRROR=mirrors.ustc.edu.cn
      dockerfile: Dockerfile


    container_name: build_box
    image: build_whl
    env_file:
      - docker-runtimes.env

    # if you want to mount a local path,
    # mount it to the container path /whl.
    volumes:
#      - "$(local path):/whl"
      - $PWD/dist:/dist
      - "$PWD/build_dist.sh:/whl/build_dist.sh:ro"
    command: ["/bin/sh", "/whl/build_dist.sh"]
